import Head from 'next/head';
import Image from 'next/image';
import { GetStaticProps, NextPage, InferGetStaticPropsType } from 'next';
import BlogCard from '../components/BlogCard';
import { readPostsInfo } from '../lib/helper';
import { PostApiResponse } from '../utils/types';

type Props = InferGetStaticPropsType<typeof getStaticProps>;

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto flex max-w-3xl flex-col space-y-6 p-4">
        {posts.map((post) => (
          <BlogCard
            key={post.slug}
            title={post.title}
            description={post.meta}
            slug={post.slug}
          />
        ))}
      </div>
    </div>
  );
};

export const getStaticProps = async () => {
  const postInfo: PostApiResponse = readPostsInfo();

  return {
    props: { posts: postInfo },
  };
};

export default Home;
